name: soundcloud import

on:
  schedule:
   - cron: "0 7,14 * * *" #build everyday at hour 7 and 14 UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.PAT }}
        
    - name: d
      run: |
        echo Een lijn tekst als test
